[package]
name = "bip39"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.4" }
sha2 = "0.10.2"
hmac = "0.12.1"
unicode-normalization = "0.1.19"
pbkdf2 = "0.11.0"